[package]
name = "kiwi-store" # todo change the name
version = "0.1.0"
edition = "2021"

[dependencies]
crc32fast = "1.5.0"
stats_alloc = "0.1.10"
thiserror = "2.0.17"
anyhow = "1.0.100"

[[bin]]
name = "wikipedia_stress_test"
path = "wikipedia_stresstest/wikipedia_stress_test.rs"
